# Site settings
#==================================
title: nikhil trivedi | Museums. Technology. Social Justice.
email: me@nikhiltrivedi.com
description: >
I'm a Web Architect at a museum in Chicago and a social justice activist. As a facilitator, educator and strategic planner, my activism work focuses on institutional healing and accountability from historic traumas like colonialism, slavery, genocide and war. I'm a long-time volunteer with Resilience, Chicago's largest rape crisis center, I'm a regular contributor at The Incluseum, co-creator of <a href="https://visitorsofcolor.tumblr.com">visitorsofcolor.tumblr.com</a>, and my writing has been featured in Model View Culture, Fwd: Museums and the Journal for Museum Education. You will also find me playing guitar and stand-up bass, hiking, making herbal medicines, and drinking warm glasses of chai on cold winter nights.
baseurl: ""
url: "http://nikhiltrivedi.com"
twitter_username:     nikhiltri
instagram_username:   nikhiltri
github_username:      nikhiltri
soundcloud_username:  nikhiltri
skype_username:       nikhiltrivedi
linkedin_username:    nikhil-trivedi

collections:
- projects
- awards

# Build settings
#==================================
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

exclude: ['Gemfile', 'Gemfile.lock', '*~']