# Site settings
#==================================
title: nikhil trivedi | Museums. Technology. Social Justice.
email: me@nikhiltrivedi.com
description: >
  nikhil trivedi is a web developer, composer and activist. He works at a museum in
  Chicago developing web-based software in Java, PHP and Drupal. After hours, he
  creates music and art using a number of tools: guitar, sitar, composing noise,
  sound, and through collaborations with other artists. He's a volunteer 
  educator for Rape Victim Advocates, and participates in movements to end oppression.
  When none of that's happening, he likes to hike, make herbal medicines, and drink
  warm glasses of chai.
baseurl: ""
url: ""
twitter_username:     nikhiltri
instagram_username:   nikhiltri
github_username:      nikhiltri
soundcloud_username:  nikhiltri
skype_username:       nikhiltrivedi
linkedin_username:    nikhil-trivedi

collections:
- projects
- awards

# Build settings
#==================================
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-twitter-plugin

exclude: ['Gemfile', 'Gemfile.lock', '*~']