# Site settings
#==================================
title: nikhil trivedi | Museums. Technology. Social Justice.
email: me@nikhiltrivedi.com
description: >
  I'm an application developer at a museum in Chicago and a social justice activist.
  My activism work focuses on ending rape culture and patriarchy through my role as
  a volunteer educator for Rape Victim Advocates. I'm also a regular contributor at
  The Incluseum, co-creator of visitorsofcolor.tumblr.com, and my writing has been
  featured in Model View Culture and Fwd: Museums. You will also find me playing my
  guitar and sitar, composing noise, hiking, making herbal medicines, and drinking
  warm glasses of chai on cold winter nights.
baseurl: ""
url: ""
twitter_username:     nikhiltri
instagram_username:   nikhiltri
github_username:      nikhiltri
soundcloud_username:  nikhiltri
skype_username:       nikhiltrivedi
linkedin_username:    nikhil-trivedi

collections:
- projects
- awards

# Build settings
#==================================
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-twitter-plugin
  - jekyll-redirect-from
  
exclude: ['Gemfile', 'Gemfile.lock', '*~']